import { defineStore } from 'pinia'

export const usePlacesStore = defineStore('places', {
    state: () => {
        return {
            places: [
                {
                    id: 61,
                    title: "Cabana de luxo em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1950,
                    discountedPrice: 1800,
                    rating: { value: 4.9, qty: 120 },
                },
                {
                    id: 62,
                    title: "Apartamento aconchegante em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 720,
                    discountedPrice: 680,
                    rating: { value: 4.4, qty: 85 },
                },
                {
                    id: 63,
                    title: "Chalé na mata em Caraguatatuba",
                    city: { id: 3, name: "Ubatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 900,
                    discountedPrice: 850,
                    rating: { value: 4.6, qty: 150 },
                },
                {
                    id: 64,
                    title: "Casa com piscina em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 2500,
                    discountedPrice: 2300,
                    rating: { value: 4.8, qty: 210 },
                },
                {
                    id: 65,
                    title: "Suíte privativa em Ubatuba",
                    city: { id: 5, name: "Bertioga" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1100,
                    discountedPrice: 950,
                    rating: { value: 4.3, qty: 98 },
                },
                {
                    id: 66,
                    title: "Flat moderno no Guarujá",
                    city: { id: 6, name: "Guarujá" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 780,
                    discountedPrice: null,
                    rating: { value: 4.1, qty: 145 },
                },
                {
                    id: 67,
                    title: "Pousada rústica em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 850,
                    discountedPrice: 800,
                    rating: { value: 4.5, qty: 200 },
                },
                {
                    id: 68,
                    title: "Casa com quintal em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 650,
                    discountedPrice: 600,
                    rating: { value: 4.0, qty: 70 },
                },
                {
                    id: 69,
                    title: "Bangalô pé na areia em Caraguatatuba",
                    city: { id: 3, name: "Ubatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1200,
                    discountedPrice: 1100,
                    rating: { value: 4.7, qty: 189 },
                },
                {
                    id: 70,
                    title: "Apartamento familiar em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1100,
                    discountedPrice: 950,
                    rating: { value: 4.4, qty: 160 },
                },
                {
                    id: 71,
                    title: "Chalé rústico em Ubatuba",
                    city: { id: 5, name: "Bertioga" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 850,
                    discountedPrice: null,
                    rating: { value: 4.2, qty: 98 },
                },
                {
                    id: 72,
                    title: "Apartamento com varanda no Guarujá",
                    city: { id: 6, name: "Guarujá" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 780,
                    discountedPrice: 750,
                    rating: { value: 4.1, qty: 115 },
                },
                {
                    id: 73,
                    title: "Casa luxuosa em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 2750,
                    discountedPrice: 2500,
                    rating: { value: 4.9, qty: 220 },
                },
                {
                    id: 74,
                    title: "Cabana ecológica em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 950,
                    discountedPrice: 850,
                    rating: { value: 4.5, qty: 175 },
                },
                {
                    id: 75,
                    title: "Apartamento em condomínio em Caraguatatuba",
                    city: { id: 3, name: "Ubatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 750,
                    discountedPrice: 700,
                    rating: { value: 4.0, qty: 105 },
                },
                {
                    id: 76,
                    title: "Casa de praia em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 2200,
                    discountedPrice: 2000,
                    rating: { value: 4.8, qty: 194 },
                },
                {
                    id: 77,
                    title: "Suíte com vista para o mar em Ubatuba",
                    city: { id: 5, name: "Bertioga" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1000,
                    discountedPrice: 900,
                    rating: { value: 4.6, qty: 142 },
                },
                {
                    id: 78,
                    title: "Flat confortável no Guarujá",
                    city: { id: 6, name: "Guarujá" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 820,
                    discountedPrice: null,
                    rating: { value: 4.3, qty: 92 },
                },
                {
                    id: 79,
                    title: "Chalé charmoso em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1100,
                    discountedPrice: 1050,
                    rating: { value: 4.4, qty: 88 },
                },
                {
                    id: 80,
                    title: "Apartamento novo em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 650,
                    discountedPrice: null,
                    rating: { value: 4.0, qty: 67 },
                },
                {
                    id: 41,
                    title: "Casa pé na areia em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1200,
                    discountedPrice: 1000,
                    rating: { value: 4.5, qty: 234 },
                },
                {
                    id: 42,
                    title: "Chalé aconchegante em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 850,
                    discountedPrice: 750,
                    rating: { value: 4.3, qty: 112 },
                },
                {
                    id: 43,
                    title: "Apartamento com vista para o mar em Caraguatatuba",
                    city: { id: 3, name: "Ubatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 650,
                    discountedPrice: null,
                    rating: { value: 4.0, qty: 89 },
                },
                {
                    id: 44,
                    title: "Casa luxuosa em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 2000,
                    discountedPrice: 1800,
                    rating: { value: 4.8, qty: 145 },
                },
                {
                    id: 45,
                    title: "Suíte romântica em Ubatuba",
                    city: { id: 5, name: "Bertioga" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 900,
                    discountedPrice: 850,
                    rating: { value: 4.6, qty: 204 },
                },
                {
                    id: 46,
                    title: "Flat à beira-mar no Guarujá",
                    city: { id: 6, name: "Guarujá" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 750,
                    discountedPrice: 700,
                    rating: { value: 4.2, qty: 130 },
                },
                {
                    id: 47,
                    title: "Casa de veraneio em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1100,
                    discountedPrice: 980,
                    rating: { value: 4.4, qty: 210 },
                },
                {
                    id: 48,
                    title: "Bangalô charmoso em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 820,
                    discountedPrice: null,
                    rating: { value: 4.1, qty: 94 },
                },
                {
                    id: 49,
                    title: "Apartamento moderno em Caraguatatuba",
                    city: { id: 3, name: "Ubatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 680,
                    discountedPrice: 620,
                    rating: { value: 4.0, qty: 75 },
                },
                {
                    id: 50,
                    title: "Casa com piscina em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1750,
                    discountedPrice: 1600,
                    rating: { value: 4.7, qty: 132 },
                },
                {
                    id: 51,
                    title: "Chalé na montanha em Ubatuba",
                    city: { id: 5, name: "Bertioga" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 850,
                    discountedPrice: 800,
                    rating: { value: 4.5, qty: 168 },
                },
                {
                    id: 52,
                    title: "Apartamento com varanda no Guarujá",
                    city: { id: 6, name: "Guarujá" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 700,
                    discountedPrice: 650,
                    rating: { value: 4.3, qty: 140 },
                },
                {
                    id: 53,
                    title: "Casa de campo em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 950,
                    discountedPrice: null,
                    rating: { value: 4.1, qty: 115 },
                },
                {
                    id: 54,
                    title: "Pousada aconchegante em Bertioga",
                    city: { id: 2, name: "Caraguatatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 780,
                    discountedPrice: 730,
                    rating: { value: 4.4, qty: 190 },
                },
                {
                    id: 55,
                    title: "Cobertura de luxo em Caraguatatuba",
                    city: { id: 3, name: "Ubatuba" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1400,
                    discountedPrice: 1250,
                    rating: { value: 4.9, qty: 77 },
                },
                {
                    id: 56,
                    title: "Casa com vista para o mar em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1850,
                    discountedPrice: 1700,
                    rating: { value: 4.8, qty: 200 },
                },
                {
                    id: 57,
                    title: "Pousada rústica em Ubatuba",
                    city: { id: 5, name: "Bertioga" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 700,
                    discountedPrice: null,
                    rating: { value: 4.0, qty: 110 },
                },
                {
                    id: 58,
                    title: "Apartamento familiar no Guarujá",
                    city: { id: 6, name: "Guarujá" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 750,
                    discountedPrice: 700,
                    rating: { value: 4.2, qty: 134 },
                },
                {
                    id: 59,
                    title: "Suíte de frente para o mar em São Sebastião",
                    city: { id: 1, name: "São Sebastião" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 1100,
                    discountedPrice: 1000,
                    rating: { value: 4.7, qty: 189 },
                },
                {
                    id: 60,
                    title: "Refúgio paradisíaco em Ilhabela",
                    city: { id: 4, name: "Ilhabela" },
                    imgUrl: "https://picsum.photos/300/400",
                    regularPrice: 2100,
                    discountedPrice: null,
                    rating: { value: 5.0, qty: 102 },
                }
            ]
        }
    }
})
